translation into brazilian portuguese
yiisoft/input-http pull request #37
Opened 2024-04-08 15:15 UTC by luizcmarin

| New feature?  | ✔️

2024-04-08 18:05 UTC, samdark requested changes

2024-04-08 18:05 UTC, samdark commented on docs/guide/en/README.md
> +- [parameters resolvers](parameters-resolvers.md)
It was good as is.

2024-04-08 18:05 UTC, samdark commented on docs/guide/en/parameters-resolvers.md
> +# parameters resolvers
It was good as is.

2024-04-08 18:05 UTC, samdark commented on docs/guide/en/parameters-resolvers.md
> +[custom implementations of parameters resolver](https://github.com/yiisoft/middleware-dispatcher?tab=readme-ov-file#creating-your-own-implementation-of-parameters-resolver)
It was good as is.

2024-04-08 18:05 UTC, samdark commented on docs/guide/en/parameters-resolvers.md
> +An example of applying parameters resolver to middleware dispatcher:
It was good as is.

2024-04-17 10:59 UTC, luizcmarin commented
> https://github.com/yiisoft/input-http/actions/runs/8692486186/job/23837219643?pr=37

I didn't understand. I don't see the problem here. The syntax is similar to other lines in the same file.

2024-04-23 07:46 UTC, samdark approved these changes

2024-04-23 07:46 UTC, merged